// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// AnalogOutReset
void AnalogOutReset(const int handle, const int channel);
RcppExport SEXP _dwf4r_AnalogOutReset(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    AnalogOutReset(handle, channel);
    return R_NilValue;
END_RCPP
}
// AnalogOutConfigure
void AnalogOutConfigure(const int handle, const int channel, const int action_code);
RcppExport SEXP _dwf4r_AnalogOutConfigure(SEXP handleSEXP, SEXP channelSEXP, SEXP action_codeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type action_code(action_codeSEXP);
    AnalogOutConfigure(handle, channel, action_code);
    return R_NilValue;
END_RCPP
}
// AnalogOutStatus
std::string AnalogOutStatus(const int handle, const int channel);
RcppExport SEXP _dwf4r_AnalogOutStatus(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(AnalogOutStatus(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// AnalogOutNodeEnableSet
void AnalogOutNodeEnableSet(const int handle, const int channel, const int node, const int mode);
RcppExport SEXP _dwf4r_AnalogOutNodeEnableSet(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< const int >::type mode(modeSEXP);
    AnalogOutNodeEnableSet(handle, channel, node, mode);
    return R_NilValue;
END_RCPP
}
// AnalogOutNodeEnableGet
int AnalogOutNodeEnableGet(const int handle, const int channel, const int node);
RcppExport SEXP _dwf4r_AnalogOutNodeEnableGet(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    rcpp_result_gen = Rcpp::wrap(AnalogOutNodeEnableGet(handle, channel, node));
    return rcpp_result_gen;
END_RCPP
}
// AnalogOutNodeFunctionSet
void AnalogOutNodeFunctionSet(const int handle, const int channel, const int node, const int function_code);
RcppExport SEXP _dwf4r_AnalogOutNodeFunctionSet(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP, SEXP function_codeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< const int >::type function_code(function_codeSEXP);
    AnalogOutNodeFunctionSet(handle, channel, node, function_code);
    return R_NilValue;
END_RCPP
}
// AnalogOutNodeFunctionGet
int AnalogOutNodeFunctionGet(const int handle, const int channel, const int node);
RcppExport SEXP _dwf4r_AnalogOutNodeFunctionGet(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    rcpp_result_gen = Rcpp::wrap(AnalogOutNodeFunctionGet(handle, channel, node));
    return rcpp_result_gen;
END_RCPP
}
// AnalogOutNodeFrequencySet
void AnalogOutNodeFrequencySet(const int handle, const int channel, const int node, const double value);
RcppExport SEXP _dwf4r_AnalogOutNodeFrequencySet(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< const double >::type value(valueSEXP);
    AnalogOutNodeFrequencySet(handle, channel, node, value);
    return R_NilValue;
END_RCPP
}
// AnalogOutNodeFrequencyGet
double AnalogOutNodeFrequencyGet(const int handle, const int channel, const int node);
RcppExport SEXP _dwf4r_AnalogOutNodeFrequencyGet(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    rcpp_result_gen = Rcpp::wrap(AnalogOutNodeFrequencyGet(handle, channel, node));
    return rcpp_result_gen;
END_RCPP
}
// AnalogOutNodeAmplitudeSet
void AnalogOutNodeAmplitudeSet(const int handle, const int channel, const int node, const double value);
RcppExport SEXP _dwf4r_AnalogOutNodeAmplitudeSet(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< const double >::type value(valueSEXP);
    AnalogOutNodeAmplitudeSet(handle, channel, node, value);
    return R_NilValue;
END_RCPP
}
// AnalogOutNodeAmplitudeGet
double AnalogOutNodeAmplitudeGet(const int handle, const int channel, const int node);
RcppExport SEXP _dwf4r_AnalogOutNodeAmplitudeGet(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    rcpp_result_gen = Rcpp::wrap(AnalogOutNodeAmplitudeGet(handle, channel, node));
    return rcpp_result_gen;
END_RCPP
}
// AnalogOutNodeOffsetSet
void AnalogOutNodeOffsetSet(const int handle, const int channel, const int node, const double value);
RcppExport SEXP _dwf4r_AnalogOutNodeOffsetSet(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< const double >::type value(valueSEXP);
    AnalogOutNodeOffsetSet(handle, channel, node, value);
    return R_NilValue;
END_RCPP
}
// AnalogOutNodeOffsetGet
double AnalogOutNodeOffsetGet(const int handle, const int channel, const int node);
RcppExport SEXP _dwf4r_AnalogOutNodeOffsetGet(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    rcpp_result_gen = Rcpp::wrap(AnalogOutNodeOffsetGet(handle, channel, node));
    return rcpp_result_gen;
END_RCPP
}
// AnalogOutNodeSymmetrySet
void AnalogOutNodeSymmetrySet(const int handle, const int channel, const int node, const double value);
RcppExport SEXP _dwf4r_AnalogOutNodeSymmetrySet(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< const double >::type value(valueSEXP);
    AnalogOutNodeSymmetrySet(handle, channel, node, value);
    return R_NilValue;
END_RCPP
}
// AnalogOutNodeSymmetryGet
double AnalogOutNodeSymmetryGet(const int handle, const int channel, const int node);
RcppExport SEXP _dwf4r_AnalogOutNodeSymmetryGet(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    rcpp_result_gen = Rcpp::wrap(AnalogOutNodeSymmetryGet(handle, channel, node));
    return rcpp_result_gen;
END_RCPP
}
// AnalogOutNodePhaseSet
void AnalogOutNodePhaseSet(const int handle, const int channel, const int node, const double value);
RcppExport SEXP _dwf4r_AnalogOutNodePhaseSet(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< const double >::type value(valueSEXP);
    AnalogOutNodePhaseSet(handle, channel, node, value);
    return R_NilValue;
END_RCPP
}
// AnalogOutNodePhaseGet
double AnalogOutNodePhaseGet(const int handle, const int channel, const int node);
RcppExport SEXP _dwf4r_AnalogOutNodePhaseGet(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    rcpp_result_gen = Rcpp::wrap(AnalogOutNodePhaseGet(handle, channel, node));
    return rcpp_result_gen;
END_RCPP
}
// AnalogOutNodeDataSet
void AnalogOutNodeDataSet(const int handle, const int channel, const int node, Rcpp::NumericVector data);
RcppExport SEXP _dwf4r_AnalogOutNodeDataSet(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type data(dataSEXP);
    AnalogOutNodeDataSet(handle, channel, node, data);
    return R_NilValue;
END_RCPP
}
// AnalogOutTriggerSourceSet
void AnalogOutTriggerSourceSet(const int handle, const int channel, const int source_code);
RcppExport SEXP _dwf4r_AnalogOutTriggerSourceSet(SEXP handleSEXP, SEXP channelSEXP, SEXP source_codeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type source_code(source_codeSEXP);
    AnalogOutTriggerSourceSet(handle, channel, source_code);
    return R_NilValue;
END_RCPP
}
// AnalogOutTriggerSourceGet
int AnalogOutTriggerSourceGet(const int handle, const int channel);
RcppExport SEXP _dwf4r_AnalogOutTriggerSourceGet(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(AnalogOutTriggerSourceGet(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// AnalogOutTriggerSlopeSet
void AnalogOutTriggerSlopeSet(const int handle, const int channel, const int slope_code);
RcppExport SEXP _dwf4r_AnalogOutTriggerSlopeSet(SEXP handleSEXP, SEXP channelSEXP, SEXP slope_codeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type slope_code(slope_codeSEXP);
    AnalogOutTriggerSlopeSet(handle, channel, slope_code);
    return R_NilValue;
END_RCPP
}
// AnalogOutTriggerSlopeGet
int AnalogOutTriggerSlopeGet(const int handle, const int channel);
RcppExport SEXP _dwf4r_AnalogOutTriggerSlopeGet(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(AnalogOutTriggerSlopeGet(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// AnalogOutMasterSet
void AnalogOutMasterSet(const int handle, const int channel, const int master_channel);
RcppExport SEXP _dwf4r_AnalogOutMasterSet(SEXP handleSEXP, SEXP channelSEXP, SEXP master_channelSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type master_channel(master_channelSEXP);
    AnalogOutMasterSet(handle, channel, master_channel);
    return R_NilValue;
END_RCPP
}
// AnalogOutMasterGet
int AnalogOutMasterGet(const int handle, const int channel);
RcppExport SEXP _dwf4r_AnalogOutMasterGet(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(AnalogOutMasterGet(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// AnalogOutRunSet
void AnalogOutRunSet(const int handle, const int channel, const double time_s);
RcppExport SEXP _dwf4r_AnalogOutRunSet(SEXP handleSEXP, SEXP channelSEXP, SEXP time_sSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const double >::type time_s(time_sSEXP);
    AnalogOutRunSet(handle, channel, time_s);
    return R_NilValue;
END_RCPP
}
// AnalogOutRunGet
double AnalogOutRunGet(const int handle, const int channel);
RcppExport SEXP _dwf4r_AnalogOutRunGet(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(AnalogOutRunGet(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// AnalogOutRunStatus
double AnalogOutRunStatus(const int handle, const int channel);
RcppExport SEXP _dwf4r_AnalogOutRunStatus(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(AnalogOutRunStatus(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// AnalogOutWaitSet
void AnalogOutWaitSet(const int handle, const int channel, const double time_s);
RcppExport SEXP _dwf4r_AnalogOutWaitSet(SEXP handleSEXP, SEXP channelSEXP, SEXP time_sSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const double >::type time_s(time_sSEXP);
    AnalogOutWaitSet(handle, channel, time_s);
    return R_NilValue;
END_RCPP
}
// AnalogOutWaitGet
double AnalogOutWaitGet(const int handle, const int channel);
RcppExport SEXP _dwf4r_AnalogOutWaitGet(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(AnalogOutWaitGet(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// AnalogOutRepeatSet
void AnalogOutRepeatSet(const int handle, const int channel, const int repeat_count);
RcppExport SEXP _dwf4r_AnalogOutRepeatSet(SEXP handleSEXP, SEXP channelSEXP, SEXP repeat_countSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type repeat_count(repeat_countSEXP);
    AnalogOutRepeatSet(handle, channel, repeat_count);
    return R_NilValue;
END_RCPP
}
// AnalogOutRepeatGet
int AnalogOutRepeatGet(const int handle, const int channel);
RcppExport SEXP _dwf4r_AnalogOutRepeatGet(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(AnalogOutRepeatGet(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// AnalogOutRepeatStatus
int AnalogOutRepeatStatus(const int handle, const int channel);
RcppExport SEXP _dwf4r_AnalogOutRepeatStatus(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(AnalogOutRepeatStatus(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// AnalogOutRepeatTriggerSet
void AnalogOutRepeatTriggerSet(const int handle, const int channel, const bool repeat_trigger);
RcppExport SEXP _dwf4r_AnalogOutRepeatTriggerSet(SEXP handleSEXP, SEXP channelSEXP, SEXP repeat_triggerSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const bool >::type repeat_trigger(repeat_triggerSEXP);
    AnalogOutRepeatTriggerSet(handle, channel, repeat_trigger);
    return R_NilValue;
END_RCPP
}
// AnalogOutRepeatTriggerGet
bool AnalogOutRepeatTriggerGet(const int handle, const int channel);
RcppExport SEXP _dwf4r_AnalogOutRepeatTriggerGet(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(AnalogOutRepeatTriggerGet(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// AnalogOutIdleSet
void AnalogOutIdleSet(const int handle, const int channel, const int idle_mode_code);
RcppExport SEXP _dwf4r_AnalogOutIdleSet(SEXP handleSEXP, SEXP channelSEXP, SEXP idle_mode_codeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type idle_mode_code(idle_mode_codeSEXP);
    AnalogOutIdleSet(handle, channel, idle_mode_code);
    return R_NilValue;
END_RCPP
}
// AnalogOutIdleGet
int AnalogOutIdleGet(const int handle, const int channel);
RcppExport SEXP _dwf4r_AnalogOutIdleGet(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(AnalogOutIdleGet(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// QueryAnalogOutChannelCount
int QueryAnalogOutChannelCount(const int handle);
RcppExport SEXP _dwf4r_QueryAnalogOutChannelCount(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryAnalogOutChannelCount(handle));
    return rcpp_result_gen;
END_RCPP
}
// QueryAnalogOutChannelNodes
Rcpp::CharacterVector QueryAnalogOutChannelNodes(const int handle, const int channel);
RcppExport SEXP _dwf4r_QueryAnalogOutChannelNodes(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryAnalogOutChannelNodes(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// QueryAnalogOutRunRange
Rcpp::NumericVector QueryAnalogOutRunRange(const int handle, const int channel);
RcppExport SEXP _dwf4r_QueryAnalogOutRunRange(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryAnalogOutRunRange(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// QueryAnalogOutWaitRange
Rcpp::NumericVector QueryAnalogOutWaitRange(const int handle, const int channel);
RcppExport SEXP _dwf4r_QueryAnalogOutWaitRange(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryAnalogOutWaitRange(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// QueryAnalogOutRepeatRange
Rcpp::IntegerVector QueryAnalogOutRepeatRange(const int handle, const int channel);
RcppExport SEXP _dwf4r_QueryAnalogOutRepeatRange(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryAnalogOutRepeatRange(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// QueryAnalogOutIdleModes
Rcpp::CharacterVector QueryAnalogOutIdleModes(const int handle, const int channel);
RcppExport SEXP _dwf4r_QueryAnalogOutIdleModes(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryAnalogOutIdleModes(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// QueryAnalogOutNodeFunctionTypes
Rcpp::CharacterVector QueryAnalogOutNodeFunctionTypes(const int handle, const int channel, const int node);
RcppExport SEXP _dwf4r_QueryAnalogOutNodeFunctionTypes(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryAnalogOutNodeFunctionTypes(handle, channel, node));
    return rcpp_result_gen;
END_RCPP
}
// QueryAnalogOutNodeFrequencyRange
Rcpp::NumericVector QueryAnalogOutNodeFrequencyRange(const int handle, const int channel, const int node);
RcppExport SEXP _dwf4r_QueryAnalogOutNodeFrequencyRange(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryAnalogOutNodeFrequencyRange(handle, channel, node));
    return rcpp_result_gen;
END_RCPP
}
// QueryAnalogOutNodeAmplitudeRange
Rcpp::NumericVector QueryAnalogOutNodeAmplitudeRange(const int handle, const int channel, const int node);
RcppExport SEXP _dwf4r_QueryAnalogOutNodeAmplitudeRange(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryAnalogOutNodeAmplitudeRange(handle, channel, node));
    return rcpp_result_gen;
END_RCPP
}
// QueryAnalogOutNodeOffsetRange
Rcpp::NumericVector QueryAnalogOutNodeOffsetRange(const int handle, const int channel, const int node);
RcppExport SEXP _dwf4r_QueryAnalogOutNodeOffsetRange(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryAnalogOutNodeOffsetRange(handle, channel, node));
    return rcpp_result_gen;
END_RCPP
}
// QueryAnalogOutNodeSymmetryRange
Rcpp::NumericVector QueryAnalogOutNodeSymmetryRange(const int handle, const int channel, const int node);
RcppExport SEXP _dwf4r_QueryAnalogOutNodeSymmetryRange(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryAnalogOutNodeSymmetryRange(handle, channel, node));
    return rcpp_result_gen;
END_RCPP
}
// QueryAnalogOutNodePhaseRange
Rcpp::NumericVector QueryAnalogOutNodePhaseRange(const int handle, const int channel, const int node);
RcppExport SEXP _dwf4r_QueryAnalogOutNodePhaseRange(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryAnalogOutNodePhaseRange(handle, channel, node));
    return rcpp_result_gen;
END_RCPP
}
// QueryAnalogOutNodeSampleCountRange
Rcpp::IntegerVector QueryAnalogOutNodeSampleCountRange(const int handle, const int channel, const int node);
RcppExport SEXP _dwf4r_QueryAnalogOutNodeSampleCountRange(SEXP handleSEXP, SEXP channelSEXP, SEXP nodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type node(nodeSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryAnalogOutNodeSampleCountRange(handle, channel, node));
    return rcpp_result_gen;
END_RCPP
}
// ListDevices
Rcpp::DataFrame ListDevices(const int filter);
RcppExport SEXP _dwf4r_ListDevices(SEXP filterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type filter(filterSEXP);
    rcpp_result_gen = Rcpp::wrap(ListDevices(filter));
    return rcpp_result_gen;
END_RCPP
}
// OpenDevice
int OpenDevice(const int device_index, const int config_index);
RcppExport SEXP _dwf4r_OpenDevice(SEXP device_indexSEXP, SEXP config_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type device_index(device_indexSEXP);
    Rcpp::traits::input_parameter< const int >::type config_index(config_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(OpenDevice(device_index, config_index));
    return rcpp_result_gen;
END_RCPP
}
// DeviceAutoConfigureSet
void DeviceAutoConfigureSet(const int handle, const bool auto_configure);
RcppExport SEXP _dwf4r_DeviceAutoConfigureSet(SEXP handleSEXP, SEXP auto_configureSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const bool >::type auto_configure(auto_configureSEXP);
    DeviceAutoConfigureSet(handle, auto_configure);
    return R_NilValue;
END_RCPP
}
// CloseDevice
void CloseDevice(const int handle);
RcppExport SEXP _dwf4r_CloseDevice(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    CloseDevice(handle);
    return R_NilValue;
END_RCPP
}
// CloseAllDevices
void CloseAllDevices();
RcppExport SEXP _dwf4r_CloseAllDevices() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    CloseAllDevices();
    return R_NilValue;
END_RCPP
}
// QueryDeviceTriggerSourceMask
int QueryDeviceTriggerSourceMask(const int handle);
RcppExport SEXP _dwf4r_QueryDeviceTriggerSourceMask(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryDeviceTriggerSourceMask(handle));
    return rcpp_result_gen;
END_RCPP
}
// QueryDeviceTriggerSlopeMask
int QueryDeviceTriggerSlopeMask(const int handle);
RcppExport SEXP _dwf4r_QueryDeviceTriggerSlopeMask(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryDeviceTriggerSlopeMask(handle));
    return rcpp_result_gen;
END_RCPP
}
// DeviceTriggerPc
void DeviceTriggerPc(const int handle);
RcppExport SEXP _dwf4r_DeviceTriggerPc(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    DeviceTriggerPc(handle);
    return R_NilValue;
END_RCPP
}
// DigitalOutReset
void DigitalOutReset(const int handle);
RcppExport SEXP _dwf4r_DigitalOutReset(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    DigitalOutReset(handle);
    return R_NilValue;
END_RCPP
}
// DigitalOutConfigure
void DigitalOutConfigure(const int handle, const bool start);
RcppExport SEXP _dwf4r_DigitalOutConfigure(SEXP handleSEXP, SEXP startSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const bool >::type start(startSEXP);
    DigitalOutConfigure(handle, start);
    return R_NilValue;
END_RCPP
}
// DigitalOutStatus
std::string DigitalOutStatus(const int handle);
RcppExport SEXP _dwf4r_DigitalOutStatus(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(DigitalOutStatus(handle));
    return rcpp_result_gen;
END_RCPP
}
// DigitalOutEnableSet
void DigitalOutEnableSet(const int handle, const int channel, const bool enable);
RcppExport SEXP _dwf4r_DigitalOutEnableSet(SEXP handleSEXP, SEXP channelSEXP, SEXP enableSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const bool >::type enable(enableSEXP);
    DigitalOutEnableSet(handle, channel, enable);
    return R_NilValue;
END_RCPP
}
// DigitalOutEnableGet
bool DigitalOutEnableGet(const int handle, const int channel);
RcppExport SEXP _dwf4r_DigitalOutEnableGet(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(DigitalOutEnableGet(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// DigitalOutOutputSet
void DigitalOutOutputSet(const int handle, const int channel, const int output_code);
RcppExport SEXP _dwf4r_DigitalOutOutputSet(SEXP handleSEXP, SEXP channelSEXP, SEXP output_codeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type output_code(output_codeSEXP);
    DigitalOutOutputSet(handle, channel, output_code);
    return R_NilValue;
END_RCPP
}
// DigitalOutOutputGet
int DigitalOutOutputGet(const int handle, const int channel);
RcppExport SEXP _dwf4r_DigitalOutOutputGet(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(DigitalOutOutputGet(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// DigitalOutTypeSet
void DigitalOutTypeSet(const int handle, const int channel, const int type_code);
RcppExport SEXP _dwf4r_DigitalOutTypeSet(SEXP handleSEXP, SEXP channelSEXP, SEXP type_codeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type type_code(type_codeSEXP);
    DigitalOutTypeSet(handle, channel, type_code);
    return R_NilValue;
END_RCPP
}
// DigitalOutTypeGet
int DigitalOutTypeGet(const int handle, const int channel);
RcppExport SEXP _dwf4r_DigitalOutTypeGet(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(DigitalOutTypeGet(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// DigitalOutIdleSet
void DigitalOutIdleSet(const int handle, const int channel, const int idle_code);
RcppExport SEXP _dwf4r_DigitalOutIdleSet(SEXP handleSEXP, SEXP channelSEXP, SEXP idle_codeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const int >::type idle_code(idle_codeSEXP);
    DigitalOutIdleSet(handle, channel, idle_code);
    return R_NilValue;
END_RCPP
}
// DigitalOutIdleGet
int DigitalOutIdleGet(const int handle, const int channel);
RcppExport SEXP _dwf4r_DigitalOutIdleGet(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(DigitalOutIdleGet(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// DigitalOutDividerSet
void DigitalOutDividerSet(const int handle, const int channel, const double divider);
RcppExport SEXP _dwf4r_DigitalOutDividerSet(SEXP handleSEXP, SEXP channelSEXP, SEXP dividerSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const double >::type divider(dividerSEXP);
    DigitalOutDividerSet(handle, channel, divider);
    return R_NilValue;
END_RCPP
}
// DigitalOutDividerGet
double DigitalOutDividerGet(const int handle, const int channel);
RcppExport SEXP _dwf4r_DigitalOutDividerGet(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(DigitalOutDividerGet(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// DigitalOutDividerInitSet
void DigitalOutDividerInitSet(const int handle, const int channel, const double initial_divider);
RcppExport SEXP _dwf4r_DigitalOutDividerInitSet(SEXP handleSEXP, SEXP channelSEXP, SEXP initial_dividerSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const double >::type initial_divider(initial_dividerSEXP);
    DigitalOutDividerInitSet(handle, channel, initial_divider);
    return R_NilValue;
END_RCPP
}
// DigitalOutDividerInitGet
double DigitalOutDividerInitGet(const int handle, const int channel);
RcppExport SEXP _dwf4r_DigitalOutDividerInitGet(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(DigitalOutDividerInitGet(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// DigitalOutCounterSet
void DigitalOutCounterSet(const int handle, const int channel, const double low_count, const double high_count);
RcppExport SEXP _dwf4r_DigitalOutCounterSet(SEXP handleSEXP, SEXP channelSEXP, SEXP low_countSEXP, SEXP high_countSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const double >::type low_count(low_countSEXP);
    Rcpp::traits::input_parameter< const double >::type high_count(high_countSEXP);
    DigitalOutCounterSet(handle, channel, low_count, high_count);
    return R_NilValue;
END_RCPP
}
// DigitalOutCounterGet
Rcpp::NumericVector DigitalOutCounterGet(const int handle, const int channel);
RcppExport SEXP _dwf4r_DigitalOutCounterGet(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(DigitalOutCounterGet(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// DigitalOutCounterInitSet
void DigitalOutCounterInitSet(const int handle, const int channel, const bool initial_high, const double initial_count);
RcppExport SEXP _dwf4r_DigitalOutCounterInitSet(SEXP handleSEXP, SEXP channelSEXP, SEXP initial_highSEXP, SEXP initial_countSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const bool >::type initial_high(initial_highSEXP);
    Rcpp::traits::input_parameter< const double >::type initial_count(initial_countSEXP);
    DigitalOutCounterInitSet(handle, channel, initial_high, initial_count);
    return R_NilValue;
END_RCPP
}
// DigitalOutCounterInitGet
Rcpp::List DigitalOutCounterInitGet(const int handle, const int channel);
RcppExport SEXP _dwf4r_DigitalOutCounterInitGet(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(DigitalOutCounterInitGet(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// DigitalOutDataSet
void DigitalOutDataSet(const int handle, const int channel, Rcpp::RawVector data, const unsigned int n_bits);
RcppExport SEXP _dwf4r_DigitalOutDataSet(SEXP handleSEXP, SEXP channelSEXP, SEXP dataSEXP, SEXP n_bitsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type n_bits(n_bitsSEXP);
    DigitalOutDataSet(handle, channel, data, n_bits);
    return R_NilValue;
END_RCPP
}
// DigitalOutRunSet
void DigitalOutRunSet(const int handle, const double time_s);
RcppExport SEXP _dwf4r_DigitalOutRunSet(SEXP handleSEXP, SEXP time_sSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const double >::type time_s(time_sSEXP);
    DigitalOutRunSet(handle, time_s);
    return R_NilValue;
END_RCPP
}
// DigitalOutRunGet
double DigitalOutRunGet(const int handle);
RcppExport SEXP _dwf4r_DigitalOutRunGet(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(DigitalOutRunGet(handle));
    return rcpp_result_gen;
END_RCPP
}
// DigitalOutRunStatus
double DigitalOutRunStatus(const int handle);
RcppExport SEXP _dwf4r_DigitalOutRunStatus(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(DigitalOutRunStatus(handle));
    return rcpp_result_gen;
END_RCPP
}
// DigitalOutWaitSet
void DigitalOutWaitSet(const int handle, const double time_s);
RcppExport SEXP _dwf4r_DigitalOutWaitSet(SEXP handleSEXP, SEXP time_sSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const double >::type time_s(time_sSEXP);
    DigitalOutWaitSet(handle, time_s);
    return R_NilValue;
END_RCPP
}
// DigitalOutWaitGet
double DigitalOutWaitGet(const int handle);
RcppExport SEXP _dwf4r_DigitalOutWaitGet(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(DigitalOutWaitGet(handle));
    return rcpp_result_gen;
END_RCPP
}
// DigitalOutRepeatSet
void DigitalOutRepeatSet(const int handle, const double repeat_count);
RcppExport SEXP _dwf4r_DigitalOutRepeatSet(SEXP handleSEXP, SEXP repeat_countSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const double >::type repeat_count(repeat_countSEXP);
    DigitalOutRepeatSet(handle, repeat_count);
    return R_NilValue;
END_RCPP
}
// DigitalOutRepeatGet
double DigitalOutRepeatGet(const int handle);
RcppExport SEXP _dwf4r_DigitalOutRepeatGet(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(DigitalOutRepeatGet(handle));
    return rcpp_result_gen;
END_RCPP
}
// DigitalOutRepeatStatus
double DigitalOutRepeatStatus(const int handle);
RcppExport SEXP _dwf4r_DigitalOutRepeatStatus(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(DigitalOutRepeatStatus(handle));
    return rcpp_result_gen;
END_RCPP
}
// DigitalOutTriggerSourceSet
void DigitalOutTriggerSourceSet(const int handle, const int source_code);
RcppExport SEXP _dwf4r_DigitalOutTriggerSourceSet(SEXP handleSEXP, SEXP source_codeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type source_code(source_codeSEXP);
    DigitalOutTriggerSourceSet(handle, source_code);
    return R_NilValue;
END_RCPP
}
// DigitalOutTriggerSourceGet
int DigitalOutTriggerSourceGet(const int handle);
RcppExport SEXP _dwf4r_DigitalOutTriggerSourceGet(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(DigitalOutTriggerSourceGet(handle));
    return rcpp_result_gen;
END_RCPP
}
// DigitalOutTriggerSlopeSet
void DigitalOutTriggerSlopeSet(const int handle, const int slope_code);
RcppExport SEXP _dwf4r_DigitalOutTriggerSlopeSet(SEXP handleSEXP, SEXP slope_codeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type slope_code(slope_codeSEXP);
    DigitalOutTriggerSlopeSet(handle, slope_code);
    return R_NilValue;
END_RCPP
}
// DigitalOutTriggerSlopeGet
int DigitalOutTriggerSlopeGet(const int handle);
RcppExport SEXP _dwf4r_DigitalOutTriggerSlopeGet(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(DigitalOutTriggerSlopeGet(handle));
    return rcpp_result_gen;
END_RCPP
}
// DigitalOutRepeatTriggerSet
void DigitalOutRepeatTriggerSet(const int handle, const bool repeat_trigger);
RcppExport SEXP _dwf4r_DigitalOutRepeatTriggerSet(SEXP handleSEXP, SEXP repeat_triggerSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const bool >::type repeat_trigger(repeat_triggerSEXP);
    DigitalOutRepeatTriggerSet(handle, repeat_trigger);
    return R_NilValue;
END_RCPP
}
// DigitalOutRepeatTriggerGet
bool DigitalOutRepeatTriggerGet(const int handle);
RcppExport SEXP _dwf4r_DigitalOutRepeatTriggerGet(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(DigitalOutRepeatTriggerGet(handle));
    return rcpp_result_gen;
END_RCPP
}
// QueryDigitalOutChannelCount
int QueryDigitalOutChannelCount(const int handle);
RcppExport SEXP _dwf4r_QueryDigitalOutChannelCount(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryDigitalOutChannelCount(handle));
    return rcpp_result_gen;
END_RCPP
}
// QueryDigitalOutInternalClockFrequency
double QueryDigitalOutInternalClockFrequency(const int handle);
RcppExport SEXP _dwf4r_QueryDigitalOutInternalClockFrequency(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryDigitalOutInternalClockFrequency(handle));
    return rcpp_result_gen;
END_RCPP
}
// QueryDigitalOutRunRange
Rcpp::NumericVector QueryDigitalOutRunRange(const int handle);
RcppExport SEXP _dwf4r_QueryDigitalOutRunRange(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryDigitalOutRunRange(handle));
    return rcpp_result_gen;
END_RCPP
}
// QueryDigitalOutWaitRange
Rcpp::NumericVector QueryDigitalOutWaitRange(const int handle);
RcppExport SEXP _dwf4r_QueryDigitalOutWaitRange(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryDigitalOutWaitRange(handle));
    return rcpp_result_gen;
END_RCPP
}
// QueryDigitalOutRepeatRange
Rcpp::NumericVector QueryDigitalOutRepeatRange(const int handle);
RcppExport SEXP _dwf4r_QueryDigitalOutRepeatRange(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryDigitalOutRepeatRange(handle));
    return rcpp_result_gen;
END_RCPP
}
// QueryDigitalOutOutputMask
int QueryDigitalOutOutputMask(const int handle, const int channel);
RcppExport SEXP _dwf4r_QueryDigitalOutOutputMask(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryDigitalOutOutputMask(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// QueryDigitalOutTypeMask
int QueryDigitalOutTypeMask(const int handle, const int channel);
RcppExport SEXP _dwf4r_QueryDigitalOutTypeMask(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryDigitalOutTypeMask(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// QueryDigitalOutIdleMask
int QueryDigitalOutIdleMask(const int handle, const int channel);
RcppExport SEXP _dwf4r_QueryDigitalOutIdleMask(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryDigitalOutIdleMask(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// QueryDigitalOutDividerRange
Rcpp::NumericVector QueryDigitalOutDividerRange(const int handle, const int channel);
RcppExport SEXP _dwf4r_QueryDigitalOutDividerRange(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryDigitalOutDividerRange(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// QueryDigitalOutCounterRange
Rcpp::NumericVector QueryDigitalOutCounterRange(const int handle, const int channel);
RcppExport SEXP _dwf4r_QueryDigitalOutCounterRange(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryDigitalOutCounterRange(handle, channel));
    return rcpp_result_gen;
END_RCPP
}
// QueryDigitalOutMaxDataBits
double QueryDigitalOutMaxDataBits(const int handle, const int channel);
RcppExport SEXP _dwf4r_QueryDigitalOutMaxDataBits(SEXP handleSEXP, SEXP channelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< const int >::type channel(channelSEXP);
    rcpp_result_gen = Rcpp::wrap(QueryDigitalOutMaxDataBits(handle, channel));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dwf4r_AnalogOutReset", (DL_FUNC) &_dwf4r_AnalogOutReset, 2},
    {"_dwf4r_AnalogOutConfigure", (DL_FUNC) &_dwf4r_AnalogOutConfigure, 3},
    {"_dwf4r_AnalogOutStatus", (DL_FUNC) &_dwf4r_AnalogOutStatus, 2},
    {"_dwf4r_AnalogOutNodeEnableSet", (DL_FUNC) &_dwf4r_AnalogOutNodeEnableSet, 4},
    {"_dwf4r_AnalogOutNodeEnableGet", (DL_FUNC) &_dwf4r_AnalogOutNodeEnableGet, 3},
    {"_dwf4r_AnalogOutNodeFunctionSet", (DL_FUNC) &_dwf4r_AnalogOutNodeFunctionSet, 4},
    {"_dwf4r_AnalogOutNodeFunctionGet", (DL_FUNC) &_dwf4r_AnalogOutNodeFunctionGet, 3},
    {"_dwf4r_AnalogOutNodeFrequencySet", (DL_FUNC) &_dwf4r_AnalogOutNodeFrequencySet, 4},
    {"_dwf4r_AnalogOutNodeFrequencyGet", (DL_FUNC) &_dwf4r_AnalogOutNodeFrequencyGet, 3},
    {"_dwf4r_AnalogOutNodeAmplitudeSet", (DL_FUNC) &_dwf4r_AnalogOutNodeAmplitudeSet, 4},
    {"_dwf4r_AnalogOutNodeAmplitudeGet", (DL_FUNC) &_dwf4r_AnalogOutNodeAmplitudeGet, 3},
    {"_dwf4r_AnalogOutNodeOffsetSet", (DL_FUNC) &_dwf4r_AnalogOutNodeOffsetSet, 4},
    {"_dwf4r_AnalogOutNodeOffsetGet", (DL_FUNC) &_dwf4r_AnalogOutNodeOffsetGet, 3},
    {"_dwf4r_AnalogOutNodeSymmetrySet", (DL_FUNC) &_dwf4r_AnalogOutNodeSymmetrySet, 4},
    {"_dwf4r_AnalogOutNodeSymmetryGet", (DL_FUNC) &_dwf4r_AnalogOutNodeSymmetryGet, 3},
    {"_dwf4r_AnalogOutNodePhaseSet", (DL_FUNC) &_dwf4r_AnalogOutNodePhaseSet, 4},
    {"_dwf4r_AnalogOutNodePhaseGet", (DL_FUNC) &_dwf4r_AnalogOutNodePhaseGet, 3},
    {"_dwf4r_AnalogOutNodeDataSet", (DL_FUNC) &_dwf4r_AnalogOutNodeDataSet, 4},
    {"_dwf4r_AnalogOutTriggerSourceSet", (DL_FUNC) &_dwf4r_AnalogOutTriggerSourceSet, 3},
    {"_dwf4r_AnalogOutTriggerSourceGet", (DL_FUNC) &_dwf4r_AnalogOutTriggerSourceGet, 2},
    {"_dwf4r_AnalogOutTriggerSlopeSet", (DL_FUNC) &_dwf4r_AnalogOutTriggerSlopeSet, 3},
    {"_dwf4r_AnalogOutTriggerSlopeGet", (DL_FUNC) &_dwf4r_AnalogOutTriggerSlopeGet, 2},
    {"_dwf4r_AnalogOutMasterSet", (DL_FUNC) &_dwf4r_AnalogOutMasterSet, 3},
    {"_dwf4r_AnalogOutMasterGet", (DL_FUNC) &_dwf4r_AnalogOutMasterGet, 2},
    {"_dwf4r_AnalogOutRunSet", (DL_FUNC) &_dwf4r_AnalogOutRunSet, 3},
    {"_dwf4r_AnalogOutRunGet", (DL_FUNC) &_dwf4r_AnalogOutRunGet, 2},
    {"_dwf4r_AnalogOutRunStatus", (DL_FUNC) &_dwf4r_AnalogOutRunStatus, 2},
    {"_dwf4r_AnalogOutWaitSet", (DL_FUNC) &_dwf4r_AnalogOutWaitSet, 3},
    {"_dwf4r_AnalogOutWaitGet", (DL_FUNC) &_dwf4r_AnalogOutWaitGet, 2},
    {"_dwf4r_AnalogOutRepeatSet", (DL_FUNC) &_dwf4r_AnalogOutRepeatSet, 3},
    {"_dwf4r_AnalogOutRepeatGet", (DL_FUNC) &_dwf4r_AnalogOutRepeatGet, 2},
    {"_dwf4r_AnalogOutRepeatStatus", (DL_FUNC) &_dwf4r_AnalogOutRepeatStatus, 2},
    {"_dwf4r_AnalogOutRepeatTriggerSet", (DL_FUNC) &_dwf4r_AnalogOutRepeatTriggerSet, 3},
    {"_dwf4r_AnalogOutRepeatTriggerGet", (DL_FUNC) &_dwf4r_AnalogOutRepeatTriggerGet, 2},
    {"_dwf4r_AnalogOutIdleSet", (DL_FUNC) &_dwf4r_AnalogOutIdleSet, 3},
    {"_dwf4r_AnalogOutIdleGet", (DL_FUNC) &_dwf4r_AnalogOutIdleGet, 2},
    {"_dwf4r_QueryAnalogOutChannelCount", (DL_FUNC) &_dwf4r_QueryAnalogOutChannelCount, 1},
    {"_dwf4r_QueryAnalogOutChannelNodes", (DL_FUNC) &_dwf4r_QueryAnalogOutChannelNodes, 2},
    {"_dwf4r_QueryAnalogOutRunRange", (DL_FUNC) &_dwf4r_QueryAnalogOutRunRange, 2},
    {"_dwf4r_QueryAnalogOutWaitRange", (DL_FUNC) &_dwf4r_QueryAnalogOutWaitRange, 2},
    {"_dwf4r_QueryAnalogOutRepeatRange", (DL_FUNC) &_dwf4r_QueryAnalogOutRepeatRange, 2},
    {"_dwf4r_QueryAnalogOutIdleModes", (DL_FUNC) &_dwf4r_QueryAnalogOutIdleModes, 2},
    {"_dwf4r_QueryAnalogOutNodeFunctionTypes", (DL_FUNC) &_dwf4r_QueryAnalogOutNodeFunctionTypes, 3},
    {"_dwf4r_QueryAnalogOutNodeFrequencyRange", (DL_FUNC) &_dwf4r_QueryAnalogOutNodeFrequencyRange, 3},
    {"_dwf4r_QueryAnalogOutNodeAmplitudeRange", (DL_FUNC) &_dwf4r_QueryAnalogOutNodeAmplitudeRange, 3},
    {"_dwf4r_QueryAnalogOutNodeOffsetRange", (DL_FUNC) &_dwf4r_QueryAnalogOutNodeOffsetRange, 3},
    {"_dwf4r_QueryAnalogOutNodeSymmetryRange", (DL_FUNC) &_dwf4r_QueryAnalogOutNodeSymmetryRange, 3},
    {"_dwf4r_QueryAnalogOutNodePhaseRange", (DL_FUNC) &_dwf4r_QueryAnalogOutNodePhaseRange, 3},
    {"_dwf4r_QueryAnalogOutNodeSampleCountRange", (DL_FUNC) &_dwf4r_QueryAnalogOutNodeSampleCountRange, 3},
    {"_dwf4r_ListDevices", (DL_FUNC) &_dwf4r_ListDevices, 1},
    {"_dwf4r_OpenDevice", (DL_FUNC) &_dwf4r_OpenDevice, 2},
    {"_dwf4r_DeviceAutoConfigureSet", (DL_FUNC) &_dwf4r_DeviceAutoConfigureSet, 2},
    {"_dwf4r_CloseDevice", (DL_FUNC) &_dwf4r_CloseDevice, 1},
    {"_dwf4r_CloseAllDevices", (DL_FUNC) &_dwf4r_CloseAllDevices, 0},
    {"_dwf4r_QueryDeviceTriggerSourceMask", (DL_FUNC) &_dwf4r_QueryDeviceTriggerSourceMask, 1},
    {"_dwf4r_QueryDeviceTriggerSlopeMask", (DL_FUNC) &_dwf4r_QueryDeviceTriggerSlopeMask, 1},
    {"_dwf4r_DeviceTriggerPc", (DL_FUNC) &_dwf4r_DeviceTriggerPc, 1},
    {"_dwf4r_DigitalOutReset", (DL_FUNC) &_dwf4r_DigitalOutReset, 1},
    {"_dwf4r_DigitalOutConfigure", (DL_FUNC) &_dwf4r_DigitalOutConfigure, 2},
    {"_dwf4r_DigitalOutStatus", (DL_FUNC) &_dwf4r_DigitalOutStatus, 1},
    {"_dwf4r_DigitalOutEnableSet", (DL_FUNC) &_dwf4r_DigitalOutEnableSet, 3},
    {"_dwf4r_DigitalOutEnableGet", (DL_FUNC) &_dwf4r_DigitalOutEnableGet, 2},
    {"_dwf4r_DigitalOutOutputSet", (DL_FUNC) &_dwf4r_DigitalOutOutputSet, 3},
    {"_dwf4r_DigitalOutOutputGet", (DL_FUNC) &_dwf4r_DigitalOutOutputGet, 2},
    {"_dwf4r_DigitalOutTypeSet", (DL_FUNC) &_dwf4r_DigitalOutTypeSet, 3},
    {"_dwf4r_DigitalOutTypeGet", (DL_FUNC) &_dwf4r_DigitalOutTypeGet, 2},
    {"_dwf4r_DigitalOutIdleSet", (DL_FUNC) &_dwf4r_DigitalOutIdleSet, 3},
    {"_dwf4r_DigitalOutIdleGet", (DL_FUNC) &_dwf4r_DigitalOutIdleGet, 2},
    {"_dwf4r_DigitalOutDividerSet", (DL_FUNC) &_dwf4r_DigitalOutDividerSet, 3},
    {"_dwf4r_DigitalOutDividerGet", (DL_FUNC) &_dwf4r_DigitalOutDividerGet, 2},
    {"_dwf4r_DigitalOutDividerInitSet", (DL_FUNC) &_dwf4r_DigitalOutDividerInitSet, 3},
    {"_dwf4r_DigitalOutDividerInitGet", (DL_FUNC) &_dwf4r_DigitalOutDividerInitGet, 2},
    {"_dwf4r_DigitalOutCounterSet", (DL_FUNC) &_dwf4r_DigitalOutCounterSet, 4},
    {"_dwf4r_DigitalOutCounterGet", (DL_FUNC) &_dwf4r_DigitalOutCounterGet, 2},
    {"_dwf4r_DigitalOutCounterInitSet", (DL_FUNC) &_dwf4r_DigitalOutCounterInitSet, 4},
    {"_dwf4r_DigitalOutCounterInitGet", (DL_FUNC) &_dwf4r_DigitalOutCounterInitGet, 2},
    {"_dwf4r_DigitalOutDataSet", (DL_FUNC) &_dwf4r_DigitalOutDataSet, 4},
    {"_dwf4r_DigitalOutRunSet", (DL_FUNC) &_dwf4r_DigitalOutRunSet, 2},
    {"_dwf4r_DigitalOutRunGet", (DL_FUNC) &_dwf4r_DigitalOutRunGet, 1},
    {"_dwf4r_DigitalOutRunStatus", (DL_FUNC) &_dwf4r_DigitalOutRunStatus, 1},
    {"_dwf4r_DigitalOutWaitSet", (DL_FUNC) &_dwf4r_DigitalOutWaitSet, 2},
    {"_dwf4r_DigitalOutWaitGet", (DL_FUNC) &_dwf4r_DigitalOutWaitGet, 1},
    {"_dwf4r_DigitalOutRepeatSet", (DL_FUNC) &_dwf4r_DigitalOutRepeatSet, 2},
    {"_dwf4r_DigitalOutRepeatGet", (DL_FUNC) &_dwf4r_DigitalOutRepeatGet, 1},
    {"_dwf4r_DigitalOutRepeatStatus", (DL_FUNC) &_dwf4r_DigitalOutRepeatStatus, 1},
    {"_dwf4r_DigitalOutTriggerSourceSet", (DL_FUNC) &_dwf4r_DigitalOutTriggerSourceSet, 2},
    {"_dwf4r_DigitalOutTriggerSourceGet", (DL_FUNC) &_dwf4r_DigitalOutTriggerSourceGet, 1},
    {"_dwf4r_DigitalOutTriggerSlopeSet", (DL_FUNC) &_dwf4r_DigitalOutTriggerSlopeSet, 2},
    {"_dwf4r_DigitalOutTriggerSlopeGet", (DL_FUNC) &_dwf4r_DigitalOutTriggerSlopeGet, 1},
    {"_dwf4r_DigitalOutRepeatTriggerSet", (DL_FUNC) &_dwf4r_DigitalOutRepeatTriggerSet, 2},
    {"_dwf4r_DigitalOutRepeatTriggerGet", (DL_FUNC) &_dwf4r_DigitalOutRepeatTriggerGet, 1},
    {"_dwf4r_QueryDigitalOutChannelCount", (DL_FUNC) &_dwf4r_QueryDigitalOutChannelCount, 1},
    {"_dwf4r_QueryDigitalOutInternalClockFrequency", (DL_FUNC) &_dwf4r_QueryDigitalOutInternalClockFrequency, 1},
    {"_dwf4r_QueryDigitalOutRunRange", (DL_FUNC) &_dwf4r_QueryDigitalOutRunRange, 1},
    {"_dwf4r_QueryDigitalOutWaitRange", (DL_FUNC) &_dwf4r_QueryDigitalOutWaitRange, 1},
    {"_dwf4r_QueryDigitalOutRepeatRange", (DL_FUNC) &_dwf4r_QueryDigitalOutRepeatRange, 1},
    {"_dwf4r_QueryDigitalOutOutputMask", (DL_FUNC) &_dwf4r_QueryDigitalOutOutputMask, 2},
    {"_dwf4r_QueryDigitalOutTypeMask", (DL_FUNC) &_dwf4r_QueryDigitalOutTypeMask, 2},
    {"_dwf4r_QueryDigitalOutIdleMask", (DL_FUNC) &_dwf4r_QueryDigitalOutIdleMask, 2},
    {"_dwf4r_QueryDigitalOutDividerRange", (DL_FUNC) &_dwf4r_QueryDigitalOutDividerRange, 2},
    {"_dwf4r_QueryDigitalOutCounterRange", (DL_FUNC) &_dwf4r_QueryDigitalOutCounterRange, 2},
    {"_dwf4r_QueryDigitalOutMaxDataBits", (DL_FUNC) &_dwf4r_QueryDigitalOutMaxDataBits, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_dwf4r(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
