# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.AnalogOutResetC <- function(handle, channel) {
    invisible(.Call(`_dwf4r_AnalogOutReset`, handle, channel))
}

.AnalogOutConfigureC <- function(handle, channel, action_code) {
    invisible(.Call(`_dwf4r_AnalogOutConfigure`, handle, channel, action_code))
}

.AnalogOutStatusC <- function(handle, channel) {
    .Call(`_dwf4r_AnalogOutStatus`, handle, channel)
}

.AnalogOutNodeEnableSetC <- function(handle, channel, node, mode) {
    invisible(.Call(`_dwf4r_AnalogOutNodeEnableSet`, handle, channel, node, mode))
}

.AnalogOutNodeEnableGetC <- function(handle, channel, node) {
    .Call(`_dwf4r_AnalogOutNodeEnableGet`, handle, channel, node)
}

.AnalogOutNodeFunctionSetC <- function(handle, channel, node, function_code) {
    invisible(.Call(`_dwf4r_AnalogOutNodeFunctionSet`, handle, channel, node, function_code))
}

.AnalogOutNodeFunctionGetC <- function(handle, channel, node) {
    .Call(`_dwf4r_AnalogOutNodeFunctionGet`, handle, channel, node)
}

.AnalogOutNodeFrequencySetC <- function(handle, channel, node, value) {
    invisible(.Call(`_dwf4r_AnalogOutNodeFrequencySet`, handle, channel, node, value))
}

.AnalogOutNodeFrequencyGetC <- function(handle, channel, node) {
    .Call(`_dwf4r_AnalogOutNodeFrequencyGet`, handle, channel, node)
}

.AnalogOutNodeAmplitudeSetC <- function(handle, channel, node, value) {
    invisible(.Call(`_dwf4r_AnalogOutNodeAmplitudeSet`, handle, channel, node, value))
}

.AnalogOutNodeAmplitudeGetC <- function(handle, channel, node) {
    .Call(`_dwf4r_AnalogOutNodeAmplitudeGet`, handle, channel, node)
}

.AnalogOutNodeOffsetSetC <- function(handle, channel, node, value) {
    invisible(.Call(`_dwf4r_AnalogOutNodeOffsetSet`, handle, channel, node, value))
}

.AnalogOutNodeOffsetGetC <- function(handle, channel, node) {
    .Call(`_dwf4r_AnalogOutNodeOffsetGet`, handle, channel, node)
}

.AnalogOutNodeSymmetrySetC <- function(handle, channel, node, value) {
    invisible(.Call(`_dwf4r_AnalogOutNodeSymmetrySet`, handle, channel, node, value))
}

.AnalogOutNodeSymmetryGetC <- function(handle, channel, node) {
    .Call(`_dwf4r_AnalogOutNodeSymmetryGet`, handle, channel, node)
}

.AnalogOutNodePhaseSetC <- function(handle, channel, node, value) {
    invisible(.Call(`_dwf4r_AnalogOutNodePhaseSet`, handle, channel, node, value))
}

.AnalogOutNodePhaseGetC <- function(handle, channel, node) {
    .Call(`_dwf4r_AnalogOutNodePhaseGet`, handle, channel, node)
}

.AnalogOutNodeDataSetC <- function(handle, channel, node, data) {
    invisible(.Call(`_dwf4r_AnalogOutNodeDataSet`, handle, channel, node, data))
}

.AnalogOutTriggerSourceSetC <- function(handle, channel, source_code) {
    invisible(.Call(`_dwf4r_AnalogOutTriggerSourceSet`, handle, channel, source_code))
}

.AnalogOutTriggerSourceGetC <- function(handle, channel) {
    .Call(`_dwf4r_AnalogOutTriggerSourceGet`, handle, channel)
}

.AnalogOutTriggerSlopeSetC <- function(handle, channel, slope_code) {
    invisible(.Call(`_dwf4r_AnalogOutTriggerSlopeSet`, handle, channel, slope_code))
}

.AnalogOutTriggerSlopeGetC <- function(handle, channel) {
    .Call(`_dwf4r_AnalogOutTriggerSlopeGet`, handle, channel)
}

.AnalogOutMasterSetC <- function(handle, channel, master_channel) {
    invisible(.Call(`_dwf4r_AnalogOutMasterSet`, handle, channel, master_channel))
}

.AnalogOutMasterGetC <- function(handle, channel) {
    .Call(`_dwf4r_AnalogOutMasterGet`, handle, channel)
}

.AnalogOutRunSetC <- function(handle, channel, time_s) {
    invisible(.Call(`_dwf4r_AnalogOutRunSet`, handle, channel, time_s))
}

.AnalogOutRunGetC <- function(handle, channel) {
    .Call(`_dwf4r_AnalogOutRunGet`, handle, channel)
}

.AnalogOutRunStatusC <- function(handle, channel) {
    .Call(`_dwf4r_AnalogOutRunStatus`, handle, channel)
}

.AnalogOutWaitSetC <- function(handle, channel, time_s) {
    invisible(.Call(`_dwf4r_AnalogOutWaitSet`, handle, channel, time_s))
}

.AnalogOutWaitGetC <- function(handle, channel) {
    .Call(`_dwf4r_AnalogOutWaitGet`, handle, channel)
}

.AnalogOutRepeatSetC <- function(handle, channel, repeat_count) {
    invisible(.Call(`_dwf4r_AnalogOutRepeatSet`, handle, channel, repeat_count))
}

.AnalogOutRepeatGetC <- function(handle, channel) {
    .Call(`_dwf4r_AnalogOutRepeatGet`, handle, channel)
}

.AnalogOutRepeatStatusC <- function(handle, channel) {
    .Call(`_dwf4r_AnalogOutRepeatStatus`, handle, channel)
}

.AnalogOutRepeatTriggerSetC <- function(handle, channel, repeat_trigger) {
    invisible(.Call(`_dwf4r_AnalogOutRepeatTriggerSet`, handle, channel, repeat_trigger))
}

.AnalogOutRepeatTriggerGetC <- function(handle, channel) {
    .Call(`_dwf4r_AnalogOutRepeatTriggerGet`, handle, channel)
}

.AnalogOutIdleSetC <- function(handle, channel, idle_mode_code) {
    invisible(.Call(`_dwf4r_AnalogOutIdleSet`, handle, channel, idle_mode_code))
}

.AnalogOutIdleGetC <- function(handle, channel) {
    .Call(`_dwf4r_AnalogOutIdleGet`, handle, channel)
}

.QueryAnalogOutChannelCountC <- function(handle) {
    .Call(`_dwf4r_QueryAnalogOutChannelCount`, handle)
}

.QueryAnalogOutChannelNodesC <- function(handle, channel) {
    .Call(`_dwf4r_QueryAnalogOutChannelNodes`, handle, channel)
}

.QueryAnalogOutRunRangeC <- function(handle, channel) {
    .Call(`_dwf4r_QueryAnalogOutRunRange`, handle, channel)
}

.QueryAnalogOutWaitRangeC <- function(handle, channel) {
    .Call(`_dwf4r_QueryAnalogOutWaitRange`, handle, channel)
}

.QueryAnalogOutRepeatRangeC <- function(handle, channel) {
    .Call(`_dwf4r_QueryAnalogOutRepeatRange`, handle, channel)
}

.QueryAnalogOutIdleModesC <- function(handle, channel) {
    .Call(`_dwf4r_QueryAnalogOutIdleModes`, handle, channel)
}

.QueryAnalogOutNodeFunctionTypesC <- function(handle, channel, node) {
    .Call(`_dwf4r_QueryAnalogOutNodeFunctionTypes`, handle, channel, node)
}

.QueryAnalogOutNodeFrequencyRangeC <- function(handle, channel, node) {
    .Call(`_dwf4r_QueryAnalogOutNodeFrequencyRange`, handle, channel, node)
}

.QueryAnalogOutNodeAmplitudeRangeC <- function(handle, channel, node) {
    .Call(`_dwf4r_QueryAnalogOutNodeAmplitudeRange`, handle, channel, node)
}

.QueryAnalogOutNodeOffsetRangeC <- function(handle, channel, node) {
    .Call(`_dwf4r_QueryAnalogOutNodeOffsetRange`, handle, channel, node)
}

.QueryAnalogOutNodeSymmetryRangeC <- function(handle, channel, node) {
    .Call(`_dwf4r_QueryAnalogOutNodeSymmetryRange`, handle, channel, node)
}

.QueryAnalogOutNodePhaseRangeC <- function(handle, channel, node) {
    .Call(`_dwf4r_QueryAnalogOutNodePhaseRange`, handle, channel, node)
}

.QueryAnalogOutNodeSampleCountRangeC <- function(handle, channel, node) {
    .Call(`_dwf4r_QueryAnalogOutNodeSampleCountRange`, handle, channel, node)
}

.ListDevicesC <- function(filter) {
    .Call(`_dwf4r_ListDevices`, filter)
}

.OpenDeviceC <- function(device_index, config_index) {
    .Call(`_dwf4r_OpenDevice`, device_index, config_index)
}

.DeviceAutoConfigureSetC <- function(handle, auto_configure) {
    invisible(.Call(`_dwf4r_DeviceAutoConfigureSet`, handle, auto_configure))
}

.CloseDeviceC <- function(handle) {
    invisible(.Call(`_dwf4r_CloseDevice`, handle))
}

.CloseAllDevicesC <- function() {
    invisible(.Call(`_dwf4r_CloseAllDevices`))
}

.QueryDeviceTriggerSourceMaskC <- function(handle) {
    .Call(`_dwf4r_QueryDeviceTriggerSourceMask`, handle)
}

.QueryDeviceTriggerSlopeMaskC <- function(handle) {
    .Call(`_dwf4r_QueryDeviceTriggerSlopeMask`, handle)
}

.DeviceTriggerPcC <- function(handle) {
    invisible(.Call(`_dwf4r_DeviceTriggerPc`, handle))
}

